### ISSUE TITLE
fritzing file missing parts

### ISSUE THREAD

**Issue by VinuDFrame** [enveloop/miniMO#4]
I am a first time fritzer, so this may be an issue with the user.  

When I try to load the file, the program is unable to find 5 parts.  I will attach a window capture of this.

Thanks!
Prof Frame
Vincennes University
Focused Quality Education
![minimofritzingissue](https://user-images.githubusercontent.com/32143518/33168199-1d5f40a8-d00e-11e7-94ca-6164b1e373f6.png)

**Comment by enveloop** [comment]
Hi, thanks for reporting -it looks like the file saved my local paths to the parts. I don't recall having anything custom, so this is a bit odd; I'm no expert with Fritzing either, but I'll see what I can do.

**Comment by enveloop** [comment]
Hi again! I don't know why Fritzing saved local paths, but the .fzz is a a zip file, and the .fz inside, an xml file, so I edited all the paths by hand. The file opens correctly in my computer, so please try opening it now and tell me if it works.

Also, note that the purpose of the file is only to show how to place the components on the breadboard (it's better than a picture because you can move things around), so I didn't do any work on the schematic or the pcb views.

**Comment by VinuDFrame** [comment]
Thanks for  your quick attention to this, Jose!

**Comment by enveloop** [comment]
you're very much welcome :D
